const notifications = [
  {
    id: 1,
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "Ethan Wright",
    message: "accepted your friend request.",
    typeOf: "friendRequestAccepted",
    isRead: false,
    timestamp: "10m ago",
  },
  {
    id: 2,
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Doe",
    message: "sent you a friend request.",
    typeOf: "friendRequest",
    isRead: false,
    timestamp: "2m ago",
  },
  {
    id: 3,
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    name: "Jane Smith",
    message: "posted on your wall.",
    typeOf: "newPost",
    isRead: false,
    timestamp: "10m ago",
  },
  {
    id: 4,
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    name: "Bob Brown",
    message: "liked your post.",
    typeOf: "like",
    isRead: true,
    timestamp: "1h ago",
  },
  {
    id: 5,
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Alice Johnson",
    message: "commented on your post.",
    typeOf: "comment",
    isRead: false,
    timestamp: "30m ago",
  },
  {
    id: 6,
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Charlie Davis",
    message: "reposted your post.",
    typeOf: "repost",
    isRead: true,
    timestamp: "2h ago",
  },
  {
    id: 7,
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    name: "Emily White",
    message: "has a birthday today. Wish them a happy birthday!",
    typeOf: "birthdayReminder",
    isRead: false,
    timestamp: "1d ago",
  },
  {
    id: 8,
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    name: "David Wilson",
    message: "sent you a friend request.",
    typeOf: "friendRequest",
    isRead: false,
    timestamp: "5m ago",
  },
  {
    id: 9,
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Sophia Martinez",
    message: "posted on your wall.",
    typeOf: "newPost",
    isRead: true,
    timestamp: "20m ago",
  },
  {
    id: 10,
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "James Anderson",
    message: "liked your post.",
    typeOf: "like",
    isRead: false,
    timestamp: "3h ago",
  },
  {
    id: 11,
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    name: "Olivia Thomas",
    message: "commented on your post.",
    typeOf: "comment",
    isRead: true,
    timestamp: "45m ago",
  },
  {
    id: 12,
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    name: "Michael Taylor",
    message: "reposted your post.",
    typeOf: "repost",
    isRead: false,
    timestamp: "4h ago",
  },
  {
    id: 13,
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Isabella Moore",
    message: "has a birthday today. Wish them a happy birthday!",
    typeOf: "birthdayReminder",
    isRead: true,
    timestamp: "2d ago",
  },
  {
    id: 14,
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "William Jackson",
    message: "sent you a friend request.",
    typeOf: "friendRequest",
    isRead: false,
    timestamp: "15m ago",
  },
  {
    id: 15,
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    name: "Mia Harris",
    message: "posted on your wall.",
    typeOf: "newPost",
    isRead: true,
    timestamp: "1h ago",
  },
  {
    id: 16,
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    name: "Alexander Clark",
    message: "liked your post.",
    typeOf: "like",
    isRead: false,
    timestamp: "5h ago",
  },
];

export default notifications;
